# docker-compose run --rm t4cli
version: "3"
services:
    t4cli:
        image: php
        volumes:
            - .:/app
            - ~/.t4:/root/.t4
        environment:
            - T4_PROFILE=local
        working_dir: /app
        entrypoint: ["php", "t4"]
        network_mode: "host"