# docker-compose run --rm t4cli
version: "3"
services:
    t4cli:
        image: t4clibuild
        volumes:
            - .:/app
            - ~/.t4:/root/.t4
        environment:
            - T4_PROFILE=local
        network_mode: "host"